package com.restaurant.order.saga;

public enum OrderSagaState {
    STARTED,
    CART_VALIDATION_REQUESTED,
    CART_VALIDATED,
    CART_VALIDATION_FAILED,
    PAYMENT_REQUESTED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    COMPENSATING_CART_VALIDATION,
    COMPENSATING_PAYMENT,
    SAGA_COMPLETED,
    SAGA_FAILED
}